# <center style="font-family: consolas; font-size: 32px; font-weight: bold;">PyTorch</center>
<p><center style="color:#949494; font-family: consolas; font-size: 20px;">https://pytorch.org/</center></p>

***

# <center style="font-family: consolas; font-size: 32px; font-weight: bold;">A. Tensor</center>

<font face='consolas' size=3 color=#f8000b>1. Conception and Expression</font>

In [18]:
# Tensor
import torch
import numpy as np

print(torch.__version__)

2.4.1


In [8]:
tensor = torch.tensor([1, 2, 3])

print(tensor.shape)
print(tensor)

torch.Size([3])
tensor([1, 2, 3])


In [17]:
x = torch.empty(5, 3)
print(x)

zero_tensor = torch.zeros(2, 3)
print(zero_tensor)

ones_tensor = torch.ones(2, 3)
print(ones_tensor)

rand_tensor = torch.rand(3, 3)
print(rand_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4123, 0.3504, 0.0647],
        [0.9638, 0.6396, 0.2197],
        [0.6285, 0.5899, 0.7605]])


In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# sum
result = tensor1 + tensor2
print(result)  # output: tensor([5, 7, 9])

# multiple
result = tensor1 * tensor2
print(result)  # output: tensor([4, 10, 18])

In [15]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor[0, 0])
print(tensor[:, 1])

tensor(1)
tensor([2, 5, 8])


In [ ]:
tensor = tensor.to('cuda')
tensor = tensor.to('cpu')

<font face='consolas' size=3 color=#f8000b>2. Create Tensor</font>


In [28]:
data_list = [1, 2, 3, 4, 5]
y = torch.tensor(data_list)
print(y)
list = y.tolist()
print(list)

data_array = np.array([6, 7, 8, 9, 10])
z = torch.tensor(data_array)
print(z)
array = z.numpy()
print(array)

tensor([1, 2, 3, 4, 5])
[1, 2, 3, 4, 5]
tensor([ 6,  7,  8,  9, 10], dtype=torch.int32)
[ 6  7  8  9 10]


In [20]:
xx = torch.tensor([1, 2, 3], dtype=torch.float32)
print(xx.dtype)
yy = torch.zeros(3, 3, dtype=torch.int32)
print(yy.dtype)

torch.float32
torch.int32


<font face='consolas' size=3 color=#f8000b>3. Reshape</font>

In [21]:
a = torch.tensor([1, 2, 3])
b = 2
c = a + b
print(c)

tensor([3, 4, 5])


In [25]:
aa = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(aa)
bb = aa.reshape(3, 2)
print(bb)
cc = aa.view((3, 2))
print(cc)
dd = aa.transpose(0, 1)
print(dd)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


<font face='consolas' size=3 color=#f8000b>4. Autograd 自动求导</font>

In [31]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x**2 + 3*x + 1
y.sum().backward()
print(x.grad)

tensor([7., 9.])
tensor(30., grad_fn=<SumBackward0>)


<font face='consolas' size=3 color=#f8000b>5. Backpropagation, BP</font>

In [ ]:
# Example
import torch
import torch.nn as nn
import torch.optim as optim

class LinearRegression(nn.Module):
    def __init__(self):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(1, 1)  # 输入维度为1，输出维度为1

    def forward(self, x):
        return self.linear(x)


model = LinearRegression()
criterion = nn.MSELoss()  # 均方误差损失函数

optimizer = optim.SGD(model.parameters(), lr=0.01)

x_train = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

for epoch in range(100):
    optimizer.zero_grad()  # 梯度清零
    # 前向传播
    y_pred = model(x_train)
    # 计算损失
    loss = criterion(y_pred, y_train)
    # 反向传播
    loss.backward()
    # 参数更新
    optimizer.step()